{
    'name': 'Hospital Management',
    'version': '18.0.0.1',
    'summary': 'Hospital Management system to manage Patient Data',
    'author': 'Codetrade.io',
    'depends': ['account','mail','website'],
    'website': 'https://www.codetrade.io/',
    'category': "Hospital Management",
    'data': [
        'security/ir.model.access.csv',
        'views/patient_views.xml',
        'report/report_paper_format.xml',
        'report/patient_report.xml',
        'report/patient_details_report.xml',
        'views/appointment_views.xml',
        'data/report_server_action.xml',
        'report/appointment_report.xml',
        'views/prescription_views.xml',
        'data/ir.sequence.xml',
        'report/prescription_report.xml',
        'views/administration_views.xml',
        'wizard/bed_transfer_wizard_view.xml',
        'views/intensive_patient_icu_view.xml',
        'views/intensive_apache_score_views.xml',
        'views/intensive_ecg_views.xml',
        'views/intensive_gcs_views.xml',
        'views/pediatrics_symptoms_views.xml',
        'views/new_born_baby_views.xml',
        'report/newborn_baby_report.xml',
        'views/draft_test_laboratory_view.xml',
        'wizard/lab_result_wizard_views.xml',
        'wizard/lab_test_info_views.xml',
        'views/today_lab_request_view.xml',
        'views/patient_ambulatory_care_views.xml',
        'views/patient_surgery_views.xml',
        'views/medical_service_views.xml',
        'views/medicament_list_views.xml',
        'views/patient_evaluation_views.xml',
        'wizard/invoice_confirmation_wizard.xml',
        'wizard/prescription_invoice_wizard.xml',
        'wizard/lab_test_invoice_confirmation_wizard.xml',
        'wizard/medical_service_invoce.xml',
        'wizard/appointment_evaluation_per_doctor.xml',
        'views/configuration_laboratory_views.xml',
        'views/configuration_test_type_views.xml',
        'views/configuration_diseases_views.xml',
        'views/configuration_diseases.xml',
        'views/diseases_category_view.xml',
        'views/disease_structure_view.xml',
        'views/configuration_medical_procedure.xml',
        'views/configuration_health_center_views.xml',
        'views/configuration_operationl_areas_views.xml',
        'views/physician_views.xml',
        'views/configuration_medicaments_views.xml',
        'views/insaurance_views.xml',
        'views/insaurance_company_views.xml',
        'views/genetics_views.xml',
        'views/configuration_medicament_views.xml',
        'views/medical_speciality_views.xml',
        'views/medicament_unit_views.xml',
        'views/occupation_views.xml',
        'views/ethnic_group_views.xml',
        'views/recreational_drug_views.xml',
        'views/menuitems.xml',
    ],
    "assets": {
        "web.assets_backend": [
            'hospital_management/static/src/js/print_button.js'
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
