from . import patient
from . import appointments
from . import prescription
from . import administration
from . import intensive_care
from . import pediatrics
from . import newborn_baby
from . import laboratory
from . import today_lab_draft_request
from . import patient_ambulatory
from . import surgery
from . import medical_service
from . import medicament_list
from . import patient_evaluation
from . import configuration_laboratory
from . import configuration_diseases
from . import diseases_categories
from . import configuration_medical_procedure
from . import configuration_health_centers
from . import configuration_operational_areas
from . import physicians
from . import configuration_medicaments
from . import insaurance
from . import genetics
from . import configuration_medicaments
from . import configuration_misc
from . import ethnic_group
from . import recreational_drugs
